name: youtube-dl-casept
version: "2019.05.11"
summary: YouTube Downloader. READ FULL DESCRIPTION TO DOWNLOAD TO EXTERNAL STORAGE.
description: |
  youtube-dl is a small command-line program to download videos from
  YouTube.com and a few more sites. This is an unofficial snap based on the one in the snappy playpen.
  If you wish to download videos to external storage you have to run
  sudo snap connect youtube-dl-casept:removable-media core:removable-media
  after installation

base: core18
grade: stable
confinement: strict

apps:
  youtube-dl:
    command: env LC_ALL=C.UTF-8 ${SNAP}/bin/youtube-dl
    plugs: [home, network, network-bind, removable-media]

  # Same as youtube-dl, useful so that the user only has to type youtube-dl-casept instead of youtube-dl-casept.youtube-dl
  youtube-dl-casept:
    command: env LC_ALL=C.UTF-8 ${SNAP}/bin/youtube-dl
    plugs: [home, network, network-bind, removable-media]

parts:
  youtube-dl:
    source: https://github.com/rg3/youtube-dl/archive/2019.05.11.tar.gz
    plugin: python
    python-version: python3

  ffmpeg:
    source: https://ffmpeg.org/releases/ffmpeg-4.1.tar.xz
    plugin: autotools
    configflags: [--enable-openssl, --enable-gpl, --disable-doc, --enable-libass, --enable-libfreetype, --enable-libmp3lame, --enable-libopus, --enable-libtheora, --enable-libvorbis, --enable-libvpx, --enable-libx264, --enable-libx265, --enable-nonfree]
    build-packages:
      - git
      - g++
      - make
      - yasm
      - autoconf
      - libtool
      - cmake
      - pkg-config
      - automake
      - build-essential
      - libass-dev
      - libfreetype6-dev
      - libsdl1.2-dev
      - libtheora-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - texinfo
      - zlib1g-dev
      - libx264-dev
      - libmp3lame-dev
      - libopus-dev
      - libssl-dev
      - libx265-dev
      - libvpx-dev
    stage-packages:
      - libx11-6
      - libxau6
      - libxdmcp6
      - libxext6
      - libxrender1
      - libasound2
      - libass9
      - libcairo2
      - libdrm2
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgraphite2-3
      - libharfbuzz0b
      - libmp3lame0
      - libnuma1
      - libogg0
      - libopus0
      - libpixman-1-0
      - libpng16-16
      - libtheora0
      - libva-drm2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvpx5
      - libx264-152
      - libx265-146
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
    organize:
      usr/local/bin: usr/bin
