name: youtube-dl-casept
version: "2018.01.18"
summary: YouTube Downloader. READ FULL DESCRIPTION TO DOWNLOAD TO EXTERNAL STORAGE.
description: |
  youtube-dl is a small command-line program to download videos from
  YouTube.com and a few more sites. This is an unofficial snap based on the one in the snappy playpen.
  If you wish to download videos to external storage you have to run
  sudo snap connect youtube-dl-casept:removable-media core:removable-media
  after installation

grade: stable
confinement: strict

apps:
  youtube-dl:
    command: env LC_ALL=C.UTF-8 ${SNAP}/bin/youtube-dl
    plugs: [home, network, network-bind, removable-media]

parts:
  youtube-dl:
    source: https://github.com/rg3/youtube-dl/archive/2018.01.18.tar.gz
    plugin: python
    python-version: python3

  ffmpeg:
    source: https://ffmpeg.org/releases/ffmpeg-3.4.1.tar.xz
    plugin: autotools
    configflags: [--enable-gpl, --disable-doc, --enable-libass, --enable-libfreetype, --enable-libmp3lame, --enable-libopus, --enable-libtheora, --enable-libvorbis, --enable-libvpx, --enable-libx264, --enable-libx265, --enable-nonfree]
    build-packages:
      - git
      - g++
      - make
      - yasm
      - autoconf
      - libtool
      - cmake
      - pkg-config
      - automake
      - build-essential
      - libass-dev
      - libfreetype6-dev
      - libsdl1.2-dev
      - libtheora-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - texinfo
      - zlib1g-dev
      - libx264-dev
      - libmp3lame-dev
      - libopus-dev
      - libx265-dev
      - libvpx-dev
    organize:
      usr/local/bin: usr/bin
